Добавил модели данных для работы с api
mocki-toki/iOS-FakeNFT-StarterProject-Public pull request #101
Opened 2024-12-16 16:00 UTC by calvinkalin

Добавил модели:
NFTCollection - коллекция связанных nft на экране каталога
Nft - nft
Users - список пользователей на экране статистики
Profile - профиля пользователя
Currencies - список валют
Order - заказ в корзине
OrderPayment - оплата заказа

2024-12-16 16:56 UTC, mocki-toki requested changes

2024-12-16 16:56 UTC, mocki-toki commented on FakeNFT/Models/Network/NFTCollection.swift
> +struct nftCollection: Decodable {
у названий структур стиль UpperCase

2024-12-16 16:56 UTC, mocki-toki commented on FakeNFT/Models/Network/Users.swift
> +struct Users: Decodable {
дубликат

2024-12-16 17:07 UTC, MrKauperwood requested changes

2024-12-16 17:07 UTC, MrKauperwood commented on FakeNFT/Models/Network/Order.swift
> +    var id: String
А для id не лучше ли использовать UUID тип?

2024-12-16 17:07 UTC, MrKauperwood commented on FakeNFT/Models/Network/Currencies.swift
> +//
Лишний код, удали пожалуйста

2024-12-16 17:10 UTC, MrKauperwood commented
Также пофиксь пожалуйста конфликт

2024-12-16 19:09 UTC, MrKauperwood approved these changes

2024-12-17 09:44 UTC, mocki-toki requested changes
сделай пулл ветки prepair и исправь warnings от swiftlint плиз
если они будут

2024-12-17 14:38 UTC, mocki-toki approved these changes

2024-12-17 18:44 UTC, merged