Добавлен таб-бар
mocki-toki/iOS-FakeNFT-StarterProject-Public pull request #96
Opened 2024-12-15 16:28 UTC by MrKauperwood

2024-12-15 18:46 UTC, GoldenSnake approved these changes

2024-12-15 19:44 UTC, mocki-toki approved these changes

2024-12-15 19:44 UTC, mocki-toki requested changes
тут в папке Scenes лишний пробел в конце названия

2024-12-15 20:04 UTC, MrKauperwood commented
> тут в папке Scenes лишний пробел в конце названия
@mocki-toki Я удалил пробел, но это не мое изменение. Давай не будем разворачивать PR из-за изменений, которые не относятся к тем, что в нем. Спасибо за понимание!

Кстати, ты это просто заметил или уже используешь какую-то тулу типа SwiftLint?

2024-12-16 06:32 UTC, mocki-toki commented
> Кстати, ты это просто заметил или уже используешь какую-то тулу типа SwiftLint?

пока нет, просто на ревью видно было

2024-12-16 06:32 UTC, mocki-toki approved these changes

2024-12-16 07:21 UTC, merged