Настроен swiftlint
mocki-toki/iOS-FakeNFT-StarterProject-Public pull request #97
Opened 2024-12-16 07:35 UTC by mocki-toki

2024-12-16 14:51 UTC, calvinkalin approved these changes

2024-12-16 15:49 UTC, GoldenSnake approved these changes

2024-12-16 16:24 UTC, MrKauperwood requested changes
Пофиксь пожалуйста конфликты

2024-12-16 16:24 UTC, MrKauperwood commented on .swiftlint.yml
> +  - trailing_whitespace
А почему это правило пометил как disabled?

2024-12-16 16:24 UTC, MrKauperwood commented on FakeNFT/Scenes /TabBarController/TabBarController.swift
Хм, интересно, почему у тебя числится в добавленных старый файл, ты подмерживал изменения из prepare ветки?

2024-12-16 17:00 UTC, mocki-toki commented on .swiftlint.yml
> +  - trailing_whitespace
> А почему это правило пометил как disabled?

срабатывает почти в каждом файле, штатный форматтер сам подсовывает туда пробелы, поэтому если работать с этим правилом, то только с каким нибудь SwiftFormat. вообще-м больше вреда чем пользы

2024-12-16 17:02 UTC, mocki-toki commented on FakeNFT/Scenes /TabBarController/TabBarController.swift
> Хм, интересно, почему у тебя числится в добавленных старый файл, ты подмерживал изменения из prepare ветки?

да, я замержил туда изменения чтоб исправить конфликты. но видимо лучше так не делать. завтра исправлю

2024-12-17 08:07 UTC, MrKauperwood approved these changes

2024-12-17 08:38 UTC, merged